In [1]:
# Decision Tree

import pandas as pd
import numpy as np

air = pd.read_csv("./군집화_y값완성_with일시.csv", header=0)
print(air.head())

# 열 삭제하기 위해 drop 사용
air = air.drop(['Unnamed: 0'], axis = 1) # 삭제한 새로운 데이터프레임을 새로운 변수에 저장

   Unnamed: 0        측정일시    SO2   CO     O3    NO2  PM10  PM25  기온(°C)  \
0           0  2018010101  0.006  0.3  0.013  0.024  35.0  22.0    -3.3   
1           1  2018010102  0.006  0.4  0.009  0.029  38.0  27.0    -3.7   
2           2  2018010103  0.006  0.4  0.007  0.034  34.0  22.0    -4.0   
3           3  2018010104  0.007  0.3  0.006  0.034  30.0  17.0    -4.2   
4           4  2018010105  0.007  0.3  0.005  0.037  28.0  15.0    -4.4   

   풍속(m/s)  풍향(16방위)  습도(%) 대기질 등급  
0      0.7     360.0   41.0     보통  
1      0.9     270.0   42.0     나쁨  
2      1.0     290.0   44.0     나쁨  
3      1.1     290.0   53.0     보통  
4      0.8     290.0   54.0     나쁨  


In [4]:
# Ver1 : 대기 구성으로만 설정한 것

# 분류 분석에 사용할 변수 선택
X_ver1 = air[['SO2', 'CO', 'O3', 'NO2', 'PM10', 'PM25']] # 독립변수
Y_ver1 = air['대기질 등급'] # 종속변수

# 설명변수 데이터 정규화
from sklearn import preprocessing 
X_ver1 = preprocessing.StandardScaler().fit(X_ver1).transform(X_ver1)

# train-test set 데이터 분리
from sklearn.model_selection import train_test_split
X_ver1_train, X_ver1_test, Y_ver1_train, Y_ver1_test = train_test_split(X_ver1, Y_ver1, test_size=0.3, random_state=10)
#print(X_ver1_train.shape)
#print(X_ver1_test.shape)

# Decision Tree 분류 모델 생성
from sklearn import tree
tree_model_ver1 = tree.DecisionTreeClassifier(criterion='entropy', max_depth=5)
tree_model_ver1.fit(X_ver1_train, Y_ver1_train) # 학습시킴

# 예측값 생성
Y_ver1_predict = tree_model_ver1.predict(X_ver1_test)

# 출력
from sklearn import metrics
tree_matrix_ver1 = metrics.confusion_matrix(Y_ver1_test, Y_ver1_predict)
print(tree_matrix_ver1)

tree_report_ver1 = metrics.classification_report(Y_ver1_test, Y_ver1_predict)
print(tree_report_ver1)

[[771  61   8]
 [ 99 640 134]
 [ 29 195 691]]
              precision    recall  f1-score   support

          나쁨       0.86      0.92      0.89       840
          보통       0.71      0.73      0.72       873
          좋음       0.83      0.76      0.79       915

    accuracy                           0.80      2628
   macro avg       0.80      0.80      0.80      2628
weighted avg       0.80      0.80      0.80      2628



In [5]:
# Ver2 : 대기 구성으로만 설정한 것

# 분류 분석에 사용할 변수 선택
X_ver2 = air[['기온(°C)', '풍속(m/s)', '풍향(16방위)', '습도(%)']] # 독립변수
Y_ver2 = air['대기질 등급'] # 종속변수

# 설명변수 데이터 정규화
from sklearn import preprocessing 
X_ver2 = preprocessing.StandardScaler().fit(X_ver2).transform(X_ver2)

# train-test set 데이터 분리
from sklearn.model_selection import train_test_split
X_ver2_train, X_ver2_test, Y_ver2_train, Y_ver2_test = train_test_split(X_ver2, Y_ver2, test_size=0.3, random_state=10)

# Decision Tree 분류 모델 생성
from sklearn import tree
tree_model_ver2 = tree.DecisionTreeClassifier(criterion='entropy', max_depth=5)
tree_model_ver2.fit(X_ver2_train, Y_ver2_train) # 학습시킴

# 예측값 생성
Y_ver2_predict = tree_model_ver2.predict(X_ver2_test)

# 출력
from sklearn import metrics
tree_matrix_ver2 = metrics.confusion_matrix(Y_ver2_test, Y_ver2_predict)
print(tree_matrix_ver2)

tree_report_ver2 = metrics.classification_report(Y_ver2_test, Y_ver2_predict)
print(tree_report_ver2)

[[626  84 130]
 [125 652  96]
 [132  32 751]]
              precision    recall  f1-score   support

          나쁨       0.71      0.75      0.73       840
          보통       0.85      0.75      0.79       873
          좋음       0.77      0.82      0.79       915

    accuracy                           0.77      2628
   macro avg       0.78      0.77      0.77      2628
weighted avg       0.78      0.77      0.77      2628



In [21]:
# Ver3 : 대기 구성 + 기온&바람&습도로 설정한 것

# 분류 분석에 사용할 변수 선택
X_ver3 = air[['SO2', 'CO', 'O3', 'NO2', 'PM10', 'PM25', '기온(°C)', '풍속(m/s)', '풍향(16방위)', '습도(%)']] # 독립변수
Y_ver3 = air['대기질 등급'] # 종속변수

# 설명변수 데이터 정규화
from sklearn import preprocessing 
X_ver3 = preprocessing.StandardScaler().fit(X_ver3).transform(X_ver3)

# train-test set 데이터 분리
from sklearn.model_selection import train_test_split
X_ver3_train, X_ver3_test, Y_ver3_train, Y_ver3_test = train_test_split(X_ver3, Y_ver3, test_size=0.3, random_state=10)

# Decision Tree 분류 모델 생성
from sklearn import tree
tree_model_ver3 = tree.DecisionTreeClassifier(criterion='entropy', max_depth=13)
tree_model_ver3.fit(X_ver3_train, Y_ver3_train) # 학습시킴

# 예측값 생성
Y_ver3_predict = tree_model_ver3.predict(X_ver3_test)

# 출력
from sklearn import metrics
tree_matrix_ver3 = metrics.confusion_matrix(Y_ver3_test, Y_ver3_predict)
print(tree_matrix_ver3)

tree_report_ver3 = metrics.classification_report(Y_ver3_test, Y_ver3_predict)
print(tree_report_ver3)

# max_depth의 값을 5, 7, 9, 11, 13 으로 변경해 봄
# max_depth = 5
'''
[[742  56  42]
 [ 41 734  98]
 [ 32  47 836]]
              precision    recall  f1-score   support

          나쁨       0.91      0.88      0.90       840
          보통       0.88      0.84      0.86       873
          좋음       0.86      0.91      0.88       915

    accuracy                           0.88      2628
   macro avg       0.88      0.88      0.88      2628
weighted avg       0.88      0.88      0.88      2628
'''
# max_depth = 7
'''
[[759  62  19]
 [ 39 774  60]
 [ 24  57 834]]
              precision    recall  f1-score   support

          나쁨       0.92      0.90      0.91       840
          보통       0.87      0.89      0.88       873
          좋음       0.91      0.91      0.91       915

    accuracy                           0.90      2628
   macro avg       0.90      0.90      0.90      2628
weighted avg       0.90      0.90      0.90      2628
'''
# max_depth = 9
'''
[[771  51  18]
 [ 37 790  46]
 [ 22  44 849]]
              precision    recall  f1-score   support

          나쁨       0.93      0.92      0.92       840
          보통       0.89      0.90      0.90       873
          좋음       0.93      0.93      0.93       915

    accuracy                           0.92      2628
   macro avg       0.92      0.92      0.92      2628
weighted avg       0.92      0.92      0.92      2628
'''
# max_depth = 11
'''
[[776  41  23]
 [ 42 784  47]
 [ 25  48 842]]
              precision    recall  f1-score   support

          나쁨       0.92      0.92      0.92       840
          보통       0.90      0.90      0.90       873
          좋음       0.92      0.92      0.92       915

    accuracy                           0.91      2628
   macro avg       0.91      0.91      0.91      2628
weighted avg       0.91      0.91      0.91      2628
'''
# max_depth = 13
'''
[[777  43  20]
 [ 43 786  44]
 [ 23  51 841]]
              precision    recall  f1-score   support

          나쁨       0.92      0.93      0.92       840
          보통       0.89      0.90      0.90       873
          좋음       0.93      0.92      0.92       915

    accuracy                           0.91      2628
   macro avg       0.91      0.91      0.91      2628
weighted avg       0.91      0.91      0.91      2628
'''
# max_depth = 15
'''
'''

[[777  43  20]
 [ 43 786  44]
 [ 23  51 841]]
              precision    recall  f1-score   support

          나쁨       0.92      0.93      0.92       840
          보통       0.89      0.90      0.90       873
          좋음       0.93      0.92      0.92       915

    accuracy                           0.91      2628
   macro avg       0.91      0.91      0.91      2628
weighted avg       0.91      0.91      0.91      2628



'\n'