In [8]:
import pandas as pd
import numpy as np

air = pd.read_csv("./군집화_y값완성_with일시.csv", header=0)
print(air.head())

# 열 삭제하기 위해 drop 사용
air = air.drop(['Unnamed: 0'], axis = 1) # 삭제한 새로운 데이터프레임을 새로운 변수에 저장

   Unnamed: 0        측정일시    SO2   CO     O3    NO2  PM10  PM25  기온(°C)  \
0           0  2018010101  0.006  0.3  0.013  0.024  35.0  22.0    -3.3   
1           1  2018010102  0.006  0.4  0.009  0.029  38.0  27.0    -3.7   
2           2  2018010103  0.006  0.4  0.007  0.034  34.0  22.0    -4.0   
3           3  2018010104  0.007  0.3  0.006  0.034  30.0  17.0    -4.2   
4           4  2018010105  0.007  0.3  0.005  0.037  28.0  15.0    -4.4   

   풍속(m/s)  풍향(16방위)  습도(%) 대기질 등급  
0      0.7     360.0   41.0     보통  
1      0.9     270.0   42.0     나쁨  
2      1.0     290.0   44.0     나쁨  
3      1.1     290.0   53.0     보통  
4      0.8     290.0   54.0     나쁨  


In [15]:
# Ver1 : 대기 구성으로만 설정한 것

# 분류 분석에 사용할 변수 선택
X_ver1 = air[['SO2', 'CO', 'O3', 'NO2', 'PM10', 'PM25']] # 독립변수
Y_ver1 = air['대기질 등급'] # 종속변수

# KNN 분류 분석을 수행하기 위해 설명변수를 정규화(평균0, 표준편차1를 갖는 정규화 분포로)
from sklearn import preprocessing
X_ver1 = preprocessing.StandardScaler().fit(X_ver1).transform(X_ver1)

# Data set을 trainning과 test로 7:3으로 분리
from sklearn.model_selection import train_test_split
X_ver1_train, X_ver1_test, Y_ver1_train, Y_ver1_test = train_test_split(X_ver1, Y_ver1, test_size=0.3, random_state=10)

# KNN 분류 분석으로 모델 생성
from sklearn.neighbors import KNeighborsClassifier
knn_ver1 = KNeighborsClassifier(n_neighbors=9) # K의 개수를 지정해야 함
knn_ver1.fit(X_ver1_train, Y_ver1_train) # 학습시키기 위해 트레이닝 데이터 입력

# 학습 데이터로부터 생성된 모델의 예측값 생성
Y_ver1_predict = knn_ver1.predict(X_ver1_test)

from sklearn import metrics
knn_ver1_matrix = metrics.confusion_matrix(Y_ver1_test, Y_ver1_predict)
print(knn_ver1_matrix) # 결과값 행렬로 출력
knn_ver1_report = metrics.classification_report(Y_ver1_test, Y_ver1_predict)
print(knn_ver1_report)

[[771  56  13]
 [ 46 698 129]
 [ 15 142 758]]
              precision    recall  f1-score   support

          나쁨       0.93      0.92      0.92       840
          보통       0.78      0.80      0.79       873
          좋음       0.84      0.83      0.84       915

    accuracy                           0.85      2628
   macro avg       0.85      0.85      0.85      2628
weighted avg       0.85      0.85      0.85      2628



In [20]:
# Ver2 : 대기 구성으로만 설정한 것

X_ver2 = air[['기온(°C)', '풍속(m/s)', '풍향(16방위)', '습도(%)']] # 독립변수
Y_ver2 = air['대기질 등급'] # 종속변수

# KNN 분류 분석을 수행하기 위해 설명변수를 정규화(평균0, 표준편차1를 갖는 정규화 분포로)
from sklearn import preprocessing
X_ver2 = preprocessing.StandardScaler().fit(X_ver2).transform(X_ver2)

# Data set을 trainning과 test로 7:3으로 분리
from sklearn.model_selection import train_test_split
X_ver2_train, X_ver2_test, Y_ver2_train, Y_ver2_test = train_test_split(X_ver2, Y_ver2, test_size=0.3, random_state=10)

# KNN 분류 분석으로 모델 생성
from sklearn.neighbors import KNeighborsClassifier
knn_ver2 = KNeighborsClassifier(n_neighbors=9) # K의 개수를 지정해야 함
knn_ver2.fit(X_ver2_train, Y_ver2_train) # 학습시키기 위해 트레이닝 데이터 입력

# 학습 데이터로부터 생성된 모델의 예측값 생성
Y_ver2_predict = knn_ver2.predict(X_ver2_test)

from sklearn import metrics
knn_ver2_matrix = metrics.confusion_matrix(Y_ver2_test, Y_ver2_predict)
print(knn_ver2_matrix) # 결과값 행렬로 출력
knn_ver2_report = metrics.classification_report(Y_ver2_test, Y_ver2_predict)
print(knn_ver2_report)

[[613 111 116]
 [ 97 730  46]
 [117  43 755]]
              precision    recall  f1-score   support

          나쁨       0.74      0.73      0.74       840
          보통       0.83      0.84      0.83       873
          좋음       0.82      0.83      0.82       915

    accuracy                           0.80      2628
   macro avg       0.80      0.80      0.80      2628
weighted avg       0.80      0.80      0.80      2628



In [22]:
# Ver3 : 대기 구성 + 기온&바람&습도로 설정한 것

X_ver3 = air[['SO2', 'CO', 'O3', 'NO2', 'PM10', 'PM25', '기온(°C)', '풍속(m/s)', '풍향(16방위)', '습도(%)']] # 독립변수
Y_ver3 = air['대기질 등급'] # 종속변수

# KNN 분류 분석을 수행하기 위해 설명변수를 정규화(평균0, 표준편차1를 갖는 정규화 분포로)
from sklearn import preprocessing
X_ver3 = preprocessing.StandardScaler().fit(X_ver3).transform(X_ver3)

# Data set을 trainning과 test로 7:3으로 분리
from sklearn.model_selection import train_test_split
X_ver3_train, X_ver3_test, Y_ver3_train, Y_ver3_test = train_test_split(X_ver3, Y_ver3, test_size=0.3, random_state=10)

# KNN 분류 분석으로 모델 생성
from sklearn.neighbors import KNeighborsClassifier
knn_ver3 = KNeighborsClassifier(n_neighbors=9) # K의 개수를 지정해야 함
knn_ver3.fit(X_ver3_train, Y_ver3_train) # 학습시키기 위해 트레이닝 데이터 입력

# 학습 데이터로부터 생성된 모델의 예측값 생성
Y_ver3_predict = knn_ver3.predict(X_ver3_test)

from sklearn import metrics
knn_ver3_matrix = metrics.confusion_matrix(Y_ver3_test, Y_ver3_predict)
print(knn_ver3_matrix) # 결과값 행렬로 출력
knn_ver3_report = metrics.classification_report(Y_ver3_test, Y_ver3_predict)
print(knn_ver3_report)

[[800  29  11]
 [ 26 825  22]
 [ 13  25 877]]
              precision    recall  f1-score   support

          나쁨       0.95      0.95      0.95       840
          보통       0.94      0.95      0.94       873
          좋음       0.96      0.96      0.96       915

    accuracy                           0.95      2628
   macro avg       0.95      0.95      0.95      2628
weighted avg       0.95      0.95      0.95      2628



In [29]:
# Ver4 : 대기 구성 + 기온&바람&습도로 설정한 것 + k의 이웃 수 변화

knn_ver4 = KNeighborsClassifier(n_neighbors=21) # K의 개수를 지정해야 함
knn_ver4.fit(X_ver3_train, Y_ver3_train) # 학습시키기 위해 트레이닝 데이터 입력

# 학습 데이터로부터 생성된 모델의 예측값 생성
Y_ver3_predict = knn_ver4.predict(X_ver3_test)

from sklearn import metrics
knn_ver4_matrix = metrics.confusion_matrix(Y_ver3_test, Y_ver3_predict)
print(knn_ver4_matrix) # 결과값 행렬로 출력
knn_ver4_report = metrics.classification_report(Y_ver3_test, Y_ver3_predict)
print(knn_ver4_report)


# k의 이웃 수에 따른 정확도 차이
# k = 5
'''
[[800  30  10]
 [ 29 817  27]
 [ 10  27 878]]
              precision    recall  f1-score   support

          나쁨       0.95      0.95      0.95       840
          보통       0.93      0.94      0.94       873
          좋음       0.96      0.96      0.96       915

    accuracy                           0.95      2628
   macro avg       0.95      0.95      0.95      2628
weighted avg       0.95      0.95      0.95      2628
'''
# k = 7
'''
[[802  28  10]
 [ 26 821  26]
 [ 11  25 879]]
              precision    recall  f1-score   support

          나쁨       0.96      0.95      0.96       840
          보통       0.94      0.94      0.94       873
          좋음       0.96      0.96      0.96       915

    accuracy                           0.95      2628
   macro avg       0.95      0.95      0.95      2628
weighted avg       0.95      0.95      0.95      2628
'''
# k = 11
'''
[[801  26  13]
 [ 24 825  24]
 [ 11  22 882]]
              precision    recall  f1-score   support

          나쁨       0.96      0.95      0.96       840
          보통       0.95      0.95      0.95       873
          좋음       0.96      0.96      0.96       915

    accuracy                           0.95      2628
   macro avg       0.95      0.95      0.95      2628
weighted avg       0.95      0.95      0.95      2628
'''
# k = 13
'''
[[804  23  13]
 [ 22 827  24]
 [ 11  18 886]]
              precision    recall  f1-score   support

          나쁨       0.96      0.96      0.96       840
          보통       0.95      0.95      0.95       873
          좋음       0.96      0.97      0.96       915

    accuracy                           0.96      2628
   macro avg       0.96      0.96      0.96      2628
weighted avg       0.96      0.96      0.96      2628
'''
# k = 15
'''
[[802  27  11]
 [ 20 827  26]
 [ 11  22 882]]
              precision    recall  f1-score   support

          나쁨       0.96      0.95      0.96       840
          보통       0.94      0.95      0.95       873
          좋음       0.96      0.96      0.96       915

    accuracy                           0.96      2628
   macro avg       0.96      0.96      0.96      2628
weighted avg       0.96      0.96      0.96      2628
'''

[[808  26   6]
 [ 15 835  23]
 [  9  24 882]]
              precision    recall  f1-score   support

          나쁨       0.97      0.96      0.97       840
          보통       0.94      0.96      0.95       873
          좋음       0.97      0.96      0.97       915

    accuracy                           0.96      2628
   macro avg       0.96      0.96      0.96      2628
weighted avg       0.96      0.96      0.96      2628



'\n[[802  27  11]\n [ 20 827  26]\n [ 11  22 882]]\n              precision    recall  f1-score   support\n\n          나쁨       0.96      0.95      0.96       840\n          보통       0.94      0.95      0.95       873\n          좋음       0.96      0.96      0.96       915\n\n    accuracy                           0.96      2628\n   macro avg       0.96      0.96      0.96      2628\nweighted avg       0.96      0.96      0.96      2628\n'