In [22]:
import pandas as pd
import numpy as np

air = pd.read_csv("./군집화_y값완성_with일시.csv", header=0)
air.head()

Unnamed: 0        측정일시    SO2   CO     O3    NO2  PM10  PM25  기온(°C)  \
0           0  2018010101  0.006  0.3  0.013  0.024  35.0  22.0    -3.3   
1           1  2018010102  0.006  0.4  0.009  0.029  38.0  27.0    -3.7   
2           2  2018010103  0.006  0.4  0.007  0.034  34.0  22.0    -4.0   
3           3  2018010104  0.007  0.3  0.006  0.034  30.0  17.0    -4.2   
4           4  2018010105  0.007  0.3  0.005  0.037  28.0  15.0    -4.4   

   풍속(m/s)  풍향(16방위)  습도(%) 대기질 등급  
0      0.7     360.0   41.0     보통  
1      0.9     270.0   42.0     나쁨  
2      1.0     290.0   44.0     나쁨  
3      1.1     290.0   53.0     보통  
4      0.8     290.0   54.0     나쁨

In [23]:
# 열 삭제하기 위해 drop 사용
air = air.drop(['Unnamed: 0'], axis = 1) # 삭제한 새로운 데이터프레임을 새로운 변수에 저장
air.head()

측정일시    SO2   CO     O3    NO2  PM10  PM25  기온(°C)  풍속(m/s)  \
0  2018010101  0.006  0.3  0.013  0.024  35.0  22.0    -3.3      0.7   
1  2018010102  0.006  0.4  0.009  0.029  38.0  27.0    -3.7      0.9   
2  2018010103  0.006  0.4  0.007  0.034  34.0  22.0    -4.0      1.0   
3  2018010104  0.007  0.3  0.006  0.034  30.0  17.0    -4.2      1.1   
4  2018010105  0.007  0.3  0.005  0.037  28.0  15.0    -4.4      0.8   

   풍향(16방위)  습도(%) 대기질 등급  
0     360.0   41.0     보통  
1     270.0   42.0     나쁨  
2     290.0   44.0     나쁨  
3     290.0   53.0     보통  
4     290.0   54.0     나쁨

In [31]:
# Ver1 : 대기 구성으로만 설정한 것

# 분류 분석에 사용할 변수 선택
X_ver1 = nair[['SO2', 'CO', 'O3', 'NO2', 'PM10', 'PM25']] # 독립변수
Y_ver1 = nair['대기질 등급'] # 종속변수

# KNN 분류 분석을 수행하기 위해 설명변수를 정규화(평균0, 표준편차1를 갖는 정규화 분포로)
from sklearn import preprocessing
X_ver1 = preprocessing.StandardScaler().fit(X_ver1).transform(X_ver1)

# Data set을 trainning과 test로 7:3으로 분리
from sklearn.model_selection import train_test_split
X_ver1_train, X_ver1_test, Y_ver1_train, Y_ver1_test = train_test_split(X_ver1, Y_ver1, test_size=0.3, random_state=10)

In [32]:
from sklearn import svm
svm_model = svm.SVC(kernel = 'rbf')
svm_model.fit(X_ver1_train, Y_ver1_train)  #학습, 모델 생성

Y_ver1_predict = svm_model.predict(X_ver1_test)
print(Y_ver1_predict[0:10])
print(Y_ver1_test.values[0:10])

from sklearn import metrics
svm_matrix = metrics.confusion_matrix(Y_ver1_test, Y_ver1_predict)
print(svm_matrix)

svm_report = metrics.classification_report(Y_ver1_test, Y_ver1_predict)
print(svm_report)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


['나쁨' '보통' '보통' '좋음' '좋음' '나쁨' '보통' '나쁨' '보통' '좋음']
['나쁨' '보통' '보통' '좋음' '좋음' '나쁨' '나쁨' '보통' '보통' '좋음']
[[779  47  14]
 [ 40 655 178]
 [ 16 130 769]]
              precision    recall  f1-score   support

          나쁨       0.93      0.93      0.93       840
          보통       0.79      0.75      0.77       873
          좋음       0.80      0.84      0.82       915

    accuracy                           0.84      2628
   macro avg       0.84      0.84      0.84      2628
weighted avg       0.84      0.84      0.84      2628



In [26]:
# Ver2 : 기온&바람&습도로 설정한 것

X_ver2 = nair[['기온(°C)', '풍속(m/s)', '풍향(16방위)', '습도(%)']] # 독립변수
Y_ver2 = nair['대기질 등급'] # 종속변수

# Data set을 trainning과 test로 7:3으로 분리
from sklearn.model_selection import train_test_split
X_ver2_train, X_ver2_test, Y_ver2_train, Y_ver2_test = train_test_split(X_ver2, Y_ver2, test_size=0.3, random_state=10)

In [27]:
from sklearn import svm
svm_model = svm.SVC(kernel = 'rbf')
svm_model.fit(X_ver2_train, Y_ver2_train)  #학습, 모델 생성

Y_ver2_predict = svm_model.predict(X_ver2_test)
print(Y_ver2_predict[0:10])
print(Y_ver2_test.values[0:10])

from sklearn import metrics
svm_matrix = metrics.confusion_matrix(Y_ver2_test, Y_ver2_predict)
print(svm_matrix)

svm_report = metrics.classification_report(Y_ver2_test, Y_ver2_predict)
print(svm_report)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


['나쁨' '보통' '보통' '좋음' '좋음' '보통' '보통' '보통' '보통' '좋음']
['나쁨' '보통' '보통' '좋음' '좋음' '나쁨' '나쁨' '보통' '보통' '좋음']
[[546 186 108]
 [101 718  54]
 [112  74 729]]
              precision    recall  f1-score   support

          나쁨       0.72      0.65      0.68       840
          보통       0.73      0.82      0.78       873
          좋음       0.82      0.80      0.81       915

    accuracy                           0.76      2628
   macro avg       0.76      0.76      0.76      2628
weighted avg       0.76      0.76      0.76      2628



In [28]:
# Ver3 : 대기 구성 + 기온&바람&습도로 설정한 것

X_ver3 = nair[['SO2', 'CO', 'O3', 'NO2', 'PM10', 'PM25', '기온(°C)', '풍속(m/s)', '풍향(16방위)', '습도(%)']] # 독립변수
Y_ver3 = nair['대기질 등급'] # 종속변수

# Data set을 trainning과 test로 7:3으로 분리
from sklearn.model_selection import train_test_split
X_ver3_train, X_ver3_test, Y_ver3_train, Y_ver3_test = train_test_split(X_ver3, Y_ver3, test_size=0.3, random_state=10)

In [29]:
from sklearn import svm
svm_model = svm.SVC(kernel = 'rbf')
svm_model.fit(X_ver3_train, Y_ver3_train)  #학습, 모델 생성

Y_ver3_predict = svm_model.predict(X_ver3_test)
print(Y_ver3_predict[0:10])
print(Y_ver3_test.values[0:10])

from sklearn import metrics
svm_matrix = metrics.confusion_matrix(Y_ver3_test, Y_ver3_predict)
print(svm_matrix)

svm_report = metrics.classification_report(Y_ver3_test, Y_ver3_predict)
print(svm_report)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


['보통' '나쁨' '보통' '보통' '좋음' '보통' '보통' '보통' '보통' '보통']
['나쁨' '보통' '보통' '좋음' '좋음' '나쁨' '나쁨' '보통' '보통' '좋음']
[[237 579  24]
 [ 30 814  29]
 [ 10 254 651]]
              precision    recall  f1-score   support

          나쁨       0.86      0.28      0.42       840
          보통       0.49      0.93      0.65       873
          좋음       0.92      0.71      0.80       915

    accuracy                           0.65      2628
   macro avg       0.76      0.64      0.62      2628
weighted avg       0.76      0.65      0.63      2628

